### ISSUE TITLE
Restructure underlying tables to support new join workflow

### ISSUE THREAD

**Issue by mattmathis** [mattmathis/scvfa-webtools#13]
Sharpen the separation between strictly required membership columns and informational columns.

Membership columns only change on join/renew.

(In the future) informational columns may be updated at any time.

Please share for review a list of which columns are intended to go into each table, before extensive restructuring.

You can use:  [Column Partitioning in the Member DB design](https://docs.google.com/document/d/1CqfH4Kme-rBFA-B7dBqYVIdQXOBmkA50aKtq2SQd3ow/edit#bookmark=id.vqcfvyieovc)

**Comment by mbryant412** [comment]
The join process gathers only agreed upon directory information i.e. Primary Member First/Last Name, email and billing address. Upon completion of the transaction new members are prompted to add their mailing address, any secondary or child members and their directory inclusion options. All other historical/self-supplied information will be collected by the survey add-on to PMP.  This is done and can be tested per #14

**Comment by mattmathis** [comment]
On /cart:
- The red X is confusing.  Green check mark?
- I think people will comment on low contrast, but given their irrelevance, probably the right choice.  

On /checkout:
- Here it should be the billing address

I think the member name should be asked earlier (/membership-account/membership-levels ?), and then prepopulated into the billing name.  Is this reasonable?

**Comment by mbryant412** [comment]
- We don't have control over text formatting such as Bold etc. so red stood out more and signals deleting the current order rather than a green checkbox which suggest everything OK. Directions are clear Click the Red X to deleter your order and start over.
- I think we can label that Billing Address
- Member name can't go earlier without redoing the custom fields we just took out and they don't cross over to repopulate on the billing side. As before, joining member would have to enter name twice during transaction.

The billing address is all PMP cares about since the plugin is capable of storing member info for future credit card transactions. I don't recommend using this feature.

**Comment by mattmathis** [comment]
Is the X a glyph or a letter?  Can it be a little smaller and less prominent?

On: membership-account/your-profile/
- PMP Audience is not a member option.  I want to move everybody's date per #3

**Comment by mbryant412** [comment]
yes.
